#!/bin/sh

## Run this from the project root, ie sh util/install

IPATH=/opt/devicepresence

mkdir $IPATH
cp ../bin/devicepresence $IPATH/
cp -R ../www $IPATH/

## This is for hubitat
cp -R ../drivers/hubitat_plugin/config.json $IPATH/hubitat_config.json
cp ./init /etc/init.d/devicepresence
cp ./devices $IPATH/
